apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: acceptance-tests-4-9-
spec:
  pipelineRef:
    name: acceptance-tests
  timeout: 3h
  params:
  - name: ARCH
    value: "linux/amd64"
  - name: BOOTSTRAP_IMAGE
    value: quay.io/praveen4g0/kuttl-tests:v1
  - name: CATALOG_SOURCE
    value: custom-operators
  - name: CLUSTER_NAME
    value: choose_your_own_name
  - name: CHANNEL
    value: stable
  - name: GIT_PRIVATE_TEMPLATES_URI
    value: https://gitlab.cee.redhat.com/aosqe/flexy-templates.git
  - name: IS_DISCONNECTED
    value: "true"
  - name: INDEX
    value: INDEX_IMAGE
  - name: KEEP_CLUSTER
    value: "true"
  - name: LAUNCHER_VARS
    value: >-
      {
      "num_workers":3
      }
  - name: OPENSHIFT_VERSION
    value: fast-4.9
  - name: OPERATOR_ENVIRONMENT
    value: pre-stage
  - name: KUTTL_TESTS_BRANCH
    value: master
  - name: KUTTL_TESTS_DIRECTORY
    value: gitops-operator  
  - name: TEMPLATE
    value: private-templates/functionality-testing/aos-4_9/ipi-on-aws/versioned-installer-customer_vpc-disconnected
  - name: IMAGE_REPOSITORY
    value: openshift-gitops 
  workspaces:
  - name: flexy-secrets
    secret: 
      secretName: flexy
  - name: install-dir
    persistentVolumeClaim:
      claimName: install-dir
  - name: git
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 200Mi
        storageClassName: csi-manila-ceph