apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: install-dir
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      # if a pre-installed RHCOS image is not used, it will be stored in this PVC
      storage: 5Gi
  # storageClassName: csi-manila-ceph