apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: configure-operator
spec:
  workspaces:
    - name: build-artifacts
      readOnly: true
  params:
    - name: CLUSTER_NAME
      description: cluster name
    - name: CATALOG_SOURCE
      description: provide catalog-source name through which user have to subscribe operator
      default: custom-operators
    - name: IS_DISCONNECTED
      description: flag to identify disconnected nature of cluster
      default: "false"
    - name: OPERATOR_ENVIRONMENT
      description: |
          specify p12n operator environment (stage, pre-stage)
          This task is not designed for `prod` operator environment
      default: pre-stage
  steps:
    - name: configure-operator
      workingDir: /install-dir
      image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
      script: |
          #!/usr/bin/env bash
          set -euo pipefail

          if [[ $(params.OPERATOR_ENVIRONMENT) == "prod" ]]; then
            echo -e "It's not necessary to apply image content source policy and create a custom operator source in prod."
            exit 0
          fi

          # login into cluster
          oc login -u kubeadmin -p $(cat $(params.CLUSTER_NAME)/auth/kubeadmin-password) $(cat $(params.CLUSTER_NAME)/auth/api-url) --insecure-skip-tls-verify=true

          echo -e "Creating image content source policy"
          oc apply -f $(workspaces.build-artifacts.path)/image-content-source-policy.yaml

          echo -e "Waiting for nodes to get restarted"
          machines=$(oc get machineconfigpool -o=jsonpath='{.items[*].metadata.name}{" "}')

          sleep 60
          for machine in ${machines}; do
              echo -e "Waiting for machineconfigpool on node $machine to be in state Updated=true && Updating=false"
              while true; do
                sleep 3
                oc wait --for=condition=Updated=True -n openshift-operators machineconfigpool $machine --timeout=5m && \
                oc wait --for=condition=Updating=False -n openshift-operators machineconfigpool $machine --timeout=5m > /dev/null 2>&1 && \
                break
              done
          done

          echo -e "Disabling default catalog sources"
          oc patch operatorhub.config.openshift.io/cluster -p='{"spec":{"disableAllDefaultSources":true}}' --type=merge
          sleep 5

          echo -e "Creating custom catalog source"
          oc apply -f $(workspaces.build-artifacts.path)/catalog-source.yaml
          sleep 30

          echo "Waiting for pods in namespace openshift-marketplace to be ready"
          # filtering out old catalog source pod that will be removed shortly
          pods=$(oc get pods -n openshift-marketplace --sort-by={metadata.creationTimestamp} -o name | \
          grep $(params.CATALOG_SOURCE) | tail -1)

          for pod in ${pods}; do
            echo "Waiting for pod $pod in openshift-marketplace to be in ready state"
            oc wait --for=condition=Ready -n openshift-marketplace $pod --timeout=5m
          done
      volumeMounts:
      - name: install-dir
        mountPath: /install-dir
  volumes:
  - name: install-dir
    persistentVolumeClaim:
      claimName: install-dir