apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: flexy-uninstall
spec:
  workspaces:
  - name: flexy-secrets
  - name: install-dir
  params:
  - name: CLUSTER_NAME
    type: string
    description: Cluster name
  steps:
    - name: uninstall
      image: docker-registry.upshift.redhat.com/flexy/ocp4:v1.10
      workingDir: /mnt
      script: |
        #!/usr/bin/env bash

        if [ ! -d "$(workspaces.install-dir.path)/$(params.CLUSTER_NAME)" ]; then
          echo "Directory \"$(params.CLUSTER_NAME)\" does not exist. List of existing directories:"
          ls "$(workspaces.install-dir.path)" | grep -v "lost+found"
          exit 1
        fi

        while read line; do
          if [ -z "$line" ]; then continue; fi
          export "$line"
        done < $(workspaces.flexy-secrets.path)/ENVIRONMENT

        while read line; do
          if [ -z "$line" ]; then continue; fi
          export "$line"
        done < $(workspaces.install-dir.path)/$(params.CLUSTER_NAME)/envvars

        echo "Preparing environment variables and secrets"
        mkdir config
        if [[ "$VARIABLES_LOCATION" == *-on-aws* || \
              "$VARIABLES_LOCATION" == *-on-osp* ]]; then
          cp $(workspaces.flexy-secrets.path)/* config/
        else
          echo "Only AWS and PSI templates are supported."
          exit 2
        fi

        cp $(workspaces.install-dir.path)/$(params.CLUSTER_NAME)/installer-artifacts.zip .

        if [[ -z `zip -sf $(workspaces.install-dir.path)/$(params.CLUSTER_NAME)/installer-artifacts.zip | grep fips_info`
          &&  "$VARIABLES_LOCATION" == *-on-osp* ]]; then
          echo "File fips_info not found which indicates that no resources were created during installation. Skipping uninstallation script."
        elif [[ -z `zip -sf $(workspaces.install-dir.path)/$(params.CLUSTER_NAME)/installer-artifacts.zip | grep install-dir/metadata.json`
          && "$VARIABLES_LOCATION" != *osd* ]]; then
          echo "File install-dir/metadata.json not found which indicates that the installation did not start. Skipping uninstallation script."
        else
          echo "Running uninstallation script"
          ret=0
          /usr/local/bin/install_entrypoint.sh destroy || ret=$?

          if [[ "$VARIABLES_LOCATION" == *osd* ]]; then
            CLUSTER_ID=$(flexy/workdir/ocm list clusters --parameter search="name='$(params.CLUSTER_NAME)'" --columns id | sed -e 's/^ID\s*//')
            [[ -z "$CLUSTER_ID" ]] && echo "OSD cluster is no longer running." && exit 0
          else
            exit $ret
          fi
        fi
      volumeMounts:
      - name: flexy-output
        mountPath: /mnt
    - name: cleanup-cluster
      image: registry.access.redhat.com/ubi8/ubi-minimal
      workingDir: $(workspaces.install-dir.path)
      env:
        - name: UPLOADER_HOST
          valueFrom:
            secretKeyRef:
              name: uploader
              key: uploader-host
        - name: UPLOADER_USERNAME
          valueFrom:
            secretKeyRef:
              name: uploader
              key: uploader-username
        - name: UPLOADER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: uploader
              key: uploader-password
      script: |
        #!/usr/bin/env bash
        set -e

        if [ ! -d "$(workspaces.install-dir.path)/$(params.CLUSTER_NAME)" ]; then
          echo "Directory \"$(params.CLUSTER_NAME)\" does not exist. List of existing directories:"
          ls "$(workspaces.install-dir.path)" | grep -v "lost+found"
          exit 1
        fi

        echo "Removing uploaded artifacts from ${UPLOADER_HOST}"
        curl -k -s -u ${UPLOADER_USERNAME}:${UPLOADER_PASSWORD} -F path=clusters/$(params.CLUSTER_NAME) \
        -X DELETE ${UPLOADER_HOST}/upload || continue

        echo -e "\nRemoving directory $(params.CLUSTER_NAME)"
        rm -rf $(params.CLUSTER_NAME)
  volumes:
  - name: flexy-output
    emptyDir: {}