apiVersion: v1
kind: Secret
metadata:
  name: aws
type: Opaque
stringData:
  credentials: |-
    [aws-gitops]
    aws_access_key_id     = $AWS_ACCESS_KEY_ID
    aws_secret_access_key = $AWS_SECRET_ACCESS_KEY
  config: |-
    [profile aws-gitops]
    region = us-east-2
    output = text