apiVersion: v1
kind: Secret
metadata:
  name: flexy
type: Opaque
data:
  pull-secret: $PULL_SECRET
  psi-gitops-shared.pem: $SSH_PRIVATE_KEY
stringData:
  awscreds: |-
    aws_access_key_id = $AWS_ACCESS_KEY_ID
    aws_secret_access_key = $AWS_SECRET_ACCESS_KEY
  awscreds-osd: |-
    aws_access_key_id = $AWS_OSD_ACCESS_KEY_ID
    aws_secret_access_key = $AWS_OSD_SECRET_ACCESS_KEY
  config.yaml: |-
    services:
      AWS-CI:
        awscred: awscreds
        host_opts:
          user: root
          class: SSHAccessibleHost
          # AWS EC2 private key
          # https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-key-pairs.html
          # Note: You also need to put the appropriate public key into config/keys
          ssh_private_key: psi-gitops-shared.pem
        config_opts:
          region: us-east-2
        # Route53 domain
        # https://github.com/openshift/installer/blob/master/docs/user/aws/route53.md
        install_base_domain: ocp-gitops-qe.com
        cloud_type: aws
      AWS-OSD:
        awscred: awscreds-osd
        host_opts:
          user: root
          class: SSHAccessibleHost
          ssh_private_key: psi-gitops-shared.pem
        config_opts:
          region: us-east-1
        cloud_type: aws  
      openstack_upshift:
        tenant_name: "openshift-gitops"
        user: "$PSI_CLOUD_USERNAME"
        password: "$PSI_CLOUD_PASSWORD"
        domain: { name: "redhat.com" }
        url: "https://rhos-d.infra.prod.upshift.rdu2.redhat.com:13000/v3/auth/tokens"
        image: "irrelevant"
        cloud_type: openstack
        fix_hostnames: true
        floating_ip_network: false
        host_opts:
          user: root
          # path relative to your private config dir, public key expected to be .pub
          ssh_private_key: psi-gitops-shared.pem
          class: SSHAccessibleHost
      dyndns:
        user_name: "$DYNDNS_USERNAME"
        password: "$DYNDNS_PASSWORD"
        customer_name: redhat
        zone: fw.rhcloud.com
        retries: 2
        domain_suffix: fw.rhcloud.com
        end_point: "https://api2.dynect.net"
      # Openshift Cluster Management for Openshift Dedicated (OSD)
      ocm-stage:
        token_file: ocm-token-stage
        url: https://api.stage.openshift.com
        cloud: AWS-OSD
        region: us-east-1
        flavor: m5.large
        nodes: 2
        lifespan: 8h
        cloud_type: ocm
      ocm-prod:
        token_file: ocm-token-prod
        url: https://api.openshift.com
        cloud: AWS-OSD
        region: us-east-1
        flavor: m5.large
        nodes: 2
        lifespan: 8h
        cloud_type: ocm  
  psi-gitops-shared.pub: |-
    $SSH_PUBLIC_KEY
  ENVIRONMENT: |
    REG_QUAY_USER=$QUAY_IO_USERNAME
    REG_QUAY_PASSWORD=$QUAY_IO_PASSWORD
    REG_CLOUD_USER=$QUAY_IO_USERNAME
    REG_CLOUD_PASSWORD=$QUAY_IO_PASSWORD

    REG_CONNECT_USER=$REGISTRY_RH_IO_USERNAME
    REG_CONNECT_PASSWORD=$REGISTRY_RH_IO_PASSWORD
    REG_REDHAT_USER=$REGISTRY_RH_IO_USERNAME
    REG_REDHAT_PASSWORD=$REGISTRY_RH_IO_PASSWORD
  ocm-token-prod: |
    $OCM_TOKEN_PROD
  ocm-token-stage: |
    $OCM_TOKEN_STAGE